-- CreatorHubPlus Supabase target schema.
-- This file is intentionally separate from Drizzle's current MySQL schema until the
-- one-time migration is verified. It preserves legacy integer IDs for safe mapping.

create table if not exists public.users (
  id integer generated by default as identity primary key,
  "openId" text not null unique,
  name text,
  email varchar(320),
  "loginMethod" text,
  role text not null default 'user' check (role in ('user', 'admin')),
  "authUserId" uuid unique references auth.users(id) on delete set null,
  "createdAt" timestamptz not null default now(),
  "updatedAt" timestamptz not null default now(),
  "lastSignedIn" timestamptz not null default now()
);

create table if not exists public.payment_service_catalog (
  id integer generated by default as identity primary key,
  "serviceKey" text not null unique,
  "serviceLabel" text not null,
  "priceMmk" integer,
  "priceLabel" text not null default 'Quote required',
  "isActive" boolean not null default true,
  "updatedByUserId" integer references public.users(id) on delete set null,
  "createdAt" timestamptz not null default now(),
  "updatedAt" timestamptz not null default now()
);

create table if not exists public.payment_requests (
  id integer generated by default as identity primary key,
  "userId" integer not null references public.users(id) on delete cascade,
  "requestCode" text not null unique,
  "orderNumber" text not null unique,
  "paymentMethod" text not null,
  "serviceKey" text,
  "serviceLabel" text,
  "payerName" text not null,
  "accountHint" text,
  "amountMmk" integer not null,
  "quotedAmountMmk" integer,
  "paymentReference" text,
  "receiptStorageKey" text not null,
  "receiptUrl" text not null,
  "receiptName" text not null,
  "receiptContentType" text not null,
  status text not null default 'pending_review' check (status in ('pending_review', 'clarification_requested', 'verified', 'rejected')),
  "reviewNote" text,
  "reviewedByUserId" integer references public.users(id) on delete set null,
  "reviewedAt" timestamptz,
  "createdAt" timestamptz not null default now()
);

create table if not exists public.payment_notifications (
  id integer generated by default as identity primary key,
  "userId" integer not null references public.users(id) on delete cascade,
  "paymentRequestId" integer references public.payment_requests(id) on delete cascade,
  kind text not null check (kind in ('submitted', 'clarification_requested', 'verified', 'rejected')),
  title text not null,
  message text not null,
  "readAt" timestamptz,
  "createdAt" timestamptz not null default now()
);

create table if not exists public.invoices (
  id integer generated by default as identity primary key,
  "paymentRequestId" integer not null unique references public.payment_requests(id) on delete cascade,
  "userId" integer not null references public.users(id) on delete cascade,
  "invoiceNumber" text not null unique,
  "orderNumber" text not null,
  "serviceLabel" text not null,
  "customerName" text not null,
  "customerEmail" varchar(320),
  "paymentMethod" text not null,
  "amountMmk" integer not null,
  currency varchar(3) not null default 'MMK',
  status text not null default 'issued' check (status in ('issued', 'voided')),
  "pdfStorageKey" text not null,
  "pdfUrl" text not null,
  "complianceNote" text not null default 'This electronic invoice confirms a payment request marked as verified by CreatorHubPlus. Keep it for your records.',
  "issuedAt" timestamptz not null default now(),
  "createdAt" timestamptz not null default now()
);

create table if not exists public.merchant_recipients (
  id integer generated by default as identity primary key,
  "paymentMethod" text not null unique,
  "providerLabel" text not null,
  kind text not null,
  "accountName" text not null,
  "accountIdentifier" text not null,
  instructions text not null,
  "qrUrl" text,
  "qrStorageKey" text,
  "isActive" boolean not null default false,
  "createdAt" timestamptz not null default now(),
  "updatedAt" timestamptz not null default now()
);

create table if not exists public.support_cases (
  id integer generated by default as identity primary key,
  "userId" integer not null references public.users(id) on delete cascade,
  "caseCode" text not null unique,
  "serviceKey" text not null,
  "serviceLabel" text not null,
  "platformName" text not null,
  "issueSummary" text not null,
  details text not null,
  status text not null default 'open' check (status in ('open', 'clarification_requested', 'resolved', 'closed')),
  "staffNote" text,
  "reviewedByUserId" integer references public.users(id) on delete set null,
  "reviewedAt" timestamptz,
  "createdAt" timestamptz not null default now(),
  "updatedAt" timestamptz not null default now()
);

create table if not exists public.workspace_tasks (
  id integer generated by default as identity primary key,
  "userId" integer not null references public.users(id) on delete cascade,
  "viewKey" text not null default 'Today' check ("viewKey" in ('Today', 'Orbit', 'Rhythm', 'Offers')),
  title text not null,
  "durationMinutes" integer not null default 25,
  completed boolean not null default false,
  archived boolean not null default false,
  "timerSeconds" integer not null default 0,
  "sortOrder" integer not null default 0,
  "createdAt" timestamptz not null default now(),
  "updatedAt" timestamptz not null default now()
);

create table if not exists public.workspace_library_items (
  id integer generated by default as identity primary key,
  "userId" integer not null references public.users(id) on delete cascade,
  title text not null,
  kind text not null default 'template' check (kind in ('template', 'guide', 'prompt')),
  description text not null,
  pinned boolean not null default false,
  "createdAt" timestamptz not null default now(),
  "updatedAt" timestamptz not null default now()
);

create table if not exists public.workspace_settings (
  id integer generated by default as identity primary key,
  "userId" integer not null unique references public.users(id) on delete cascade,
  "studioName" text not null default 'My studio',
  "focusLengthMinutes" integer not null default 50,
  "updatedAt" timestamptz not null default now()
);

create index if not exists payment_requests_user_created_idx on public.payment_requests ("userId", "createdAt");
create index if not exists payment_requests_status_created_idx on public.payment_requests (status, "createdAt");
create index if not exists payment_notifications_user_created_idx on public.payment_notifications ("userId", "readAt", "createdAt");
create index if not exists support_cases_user_created_idx on public.support_cases ("userId", "createdAt");
create index if not exists workspace_tasks_user_view_order_idx on public.workspace_tasks ("userId", "viewKey", "sortOrder");

insert into storage.buckets (id, name, public)
values ('creatorhubplus-private', 'creatorhubplus-private', false)
on conflict (id) do nothing;

alter table public.users enable row level security;
alter table public.payment_service_catalog enable row level security;
alter table public.payment_requests enable row level security;
alter table public.payment_notifications enable row level security;
alter table public.invoices enable row level security;
alter table public.merchant_recipients enable row level security;
alter table public.support_cases enable row level security;
alter table public.workspace_tasks enable row level security;
alter table public.workspace_library_items enable row level security;
alter table public.workspace_settings enable row level security;

create or replace function public.current_creatorhubplus_user_id()
returns integer
language sql
stable
security definer
set search_path = public
as $$
  select id from public.users where "authUserId" = auth.uid() limit 1;
$$;

create or replace function public.current_creatorhubplus_is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.users
    where "authUserId" = auth.uid() and role = 'admin'
  );
$$;

create policy users_self_select on public.users for select using ("authUserId" = auth.uid() or public.current_creatorhubplus_is_admin());
create policy users_self_update on public.users for update using ("authUserId" = auth.uid() or public.current_creatorhubplus_is_admin());
create policy catalog_public_select on public.payment_service_catalog for select using ("isActive" = true or public.current_creatorhubplus_is_admin());
create policy catalog_admin_write on public.payment_service_catalog for all using (public.current_creatorhubplus_is_admin()) with check (public.current_creatorhubplus_is_admin());
create policy payment_requests_owner_select on public.payment_requests for select using ("userId" = public.current_creatorhubplus_user_id() or public.current_creatorhubplus_is_admin());
create policy payment_requests_admin_write on public.payment_requests for all using (public.current_creatorhubplus_is_admin()) with check (public.current_creatorhubplus_is_admin());
create policy notifications_owner_all on public.payment_notifications for all using ("userId" = public.current_creatorhubplus_user_id() or public.current_creatorhubplus_is_admin()) with check ("userId" = public.current_creatorhubplus_user_id() or public.current_creatorhubplus_is_admin());
create policy invoices_owner_select on public.invoices for select using ("userId" = public.current_creatorhubplus_user_id() or public.current_creatorhubplus_is_admin());
create policy invoices_admin_write on public.invoices for all using (public.current_creatorhubplus_is_admin()) with check (public.current_creatorhubplus_is_admin());
create policy recipients_public_active_select on public.merchant_recipients for select using ("isActive" = true or public.current_creatorhubplus_is_admin());
create policy recipients_admin_write on public.merchant_recipients for all using (public.current_creatorhubplus_is_admin()) with check (public.current_creatorhubplus_is_admin());
create policy cases_owner_all on public.support_cases for all using ("userId" = public.current_creatorhubplus_user_id() or public.current_creatorhubplus_is_admin()) with check ("userId" = public.current_creatorhubplus_user_id() or public.current_creatorhubplus_is_admin());
create policy workspace_tasks_owner_all on public.workspace_tasks for all using ("userId" = public.current_creatorhubplus_user_id()) with check ("userId" = public.current_creatorhubplus_user_id());
create policy workspace_library_owner_all on public.workspace_library_items for all using ("userId" = public.current_creatorhubplus_user_id()) with check ("userId" = public.current_creatorhubplus_user_id());
create policy workspace_settings_owner_all on public.workspace_settings for all using ("userId" = public.current_creatorhubplus_user_id()) with check ("userId" = public.current_creatorhubplus_user_id());

create policy private_files_owner_read on storage.objects for select using (
  bucket_id = 'creatorhubplus-private'
  and (name like 'payment-proofs/' || public.current_creatorhubplus_user_id()::text || '/%'
       or public.current_creatorhubplus_is_admin())
);
create policy private_files_owner_insert on storage.objects for insert with check (
  bucket_id = 'creatorhubplus-private'
  and name like 'payment-proofs/' || public.current_creatorhubplus_user_id()::text || '/%'
);
create policy private_files_admin_update on storage.objects for update using (bucket_id = 'creatorhubplus-private' and public.current_creatorhubplus_is_admin());
create policy private_files_admin_delete on storage.objects for delete using (bucket_id = 'creatorhubplus-private' and public.current_creatorhubplus_is_admin());
