/**
 * CreatorHubPlus — Myanmar service page
 * Language direction: formal, clear Burmese service copy; no promises beyond legitimate platform support.
 */
import { useState } from "react";
import { ArrowDownRight, ArrowUpRight, BadgeCheck, Check, ChevronDown, CircleDollarSign, CircleHelp, FileCheck2, MapPinned, Menu, MessageCircleMore, ShieldCheck, Sparkles, WalletCards, X } from "lucide-react";
import { Link } from "wouter";
import { toast } from "sonner";
import { siFacebook, siPaypal, siTiktok, siYoutube, type SimpleIcon } from "simple-icons";
import { useSiteLocale } from "@/lib/useSiteLocale";
import CaseIntakeDialog, { type CaseServiceKey } from "@/components/CaseIntakeDialog";

const logo = "/favicon.svg";
const payments = [
  { label: "KBZ Pay", logo: "/manus-storage/kbzpay_b6275ce0.webp", kind: "wallet" }, { label: "Wave Pay", logo: "/manus-storage/wavepay-appicon_9c7e244e.jpg", kind: "wallet" }, { label: "AYA Pay", logo: "/manus-storage/ayapay_385dc148.png", kind: "wallet" }, { label: "KBZ Bank", logo: "/manus-storage/kbzbank_ccd3a1fa.png", kind: "bank" }, { label: "AYA Bank", logo: "/manus-storage/ayabank_d9d29f1d.png", kind: "bank" }, { label: "Bangkok Bank", logo: "/manus-storage/bangkokbank-official_ebc198ff.svg", kind: "bank" }, { label: "KASIKORNBANK", logo: "/manus-storage/kasikornbank-official_5108252c.png", kind: "bank" },
];
const services = [
  { id: "၀၁", icon: CircleDollarSign, title: "ပလက်ဖောင်း ဝင်ငွေ", subtitle: "ဝင်ငွေရရှိရေးအတွက် အဆင်သင့်ဖြစ်မှု", state: "စစ်ဆေးရန်", next: "လက်ရှိအကောင့်အခြေအနေကို ပလက်ဖောင်း၏ ဝင်ငွေရရှိရေးလိုအပ်ချက်များနှင့် တိုက်ဆိုင်စစ်ဆေးပါ။", description: "ဝင်ငွေရရှိရေးလိုအပ်ချက်၊ အကောင့်အခြေအနေနှင့် တင်ပြရမည့်အချက်အလက်များကို စနစ်တကျ စစ်ဆေးနိုင်ပါသည်။", accent: "blue", caseKey: "platform_earnings" },
  { id: "၀၂", icon: WalletCards, title: "ငွေလက်ခံရေးနှင့် ထုတ်ယူရေး", subtitle: "ငွေလက်ခံလမ်းကြောင်းနှင့် ထုတ်ယူခြင်း", state: "လမ်းကြောင်းချမှတ်ရန်", next: "ငွေလက်ခံနည်းလမ်း၊ ဆက်လက်ဆောင်ရွက်ရမည့်အချက်နှင့် ကိုက်ညီရမည့်အသေးစိတ်ကို သတ်မှတ်ပါ။", description: "ပလက်ဖောင်းများမှ ငွေလက်ခံရန် လိုအပ်သည့်အချက်အလက်များနှင့် လုပ်ဆောင်ရန်ကျန်ရှိသည့်အဆင့်များကို ရှင်းလင်းစွာ စီမံနိုင်ပါသည်။", accent: "orange", caseKey: "payout_receiving" },
  { id: "၀၃", icon: FileCheck2, title: "အကောင့် ပြင်ဆင်သတ်မှတ်ခြင်း", subtitle: "ပြင်ဆင်သတ်မှတ်မှုနှင့် အခက်အခဲစစ်ဆေးခြင်း", state: "အတည်ပြုရန်", next: "တရားဝင် နောက်တစ်ဆင့်ကို တားဆီးနိုင်သည့် အကောင့်ဆက်တင်များကို တစ်ဆင့်ချင်း စစ်ဆေးပါ။", description: "အကောင့်အသစ်ပြင်ဆင်ခြင်း သို့မဟုတ် လက်ရှိအခက်အခဲများကို စည်းမျဉ်းနှင့်အညီ စစ်ဆေးနိုင်ရန် ကူညီပေးပါသည်။", accent: "green", caseKey: "account_setup" },
  { id: "၀၄", icon: MapPinned, title: "လိပ်စာ အတည်ပြုရေး အကူအညီ", subtitle: "အတည်ပြုနိုင်သော လိပ်စာ ပြင်ဆင်မှု", state: "ပြင်ဆင်ရန်", next: "တင်ပြမည့်အချက်အလက်များကို မပေးပို့မီ ပလက်ဖောင်းက အမှန်တကယ် အတည်ပြုနိုင်သည့်အချက်များကို စိစစ်ပါ။", description: "လိပ်စာနှင့်သက်ဆိုင်သည့် လိုအပ်ချက်များကို နားလည်ပြီး မှန်ကန်၊ တရားဝင်၊ အတည်ပြုနိုင်သော လမ်းကြောင်းဖြင့် ပြင်ဆင်နိုင်ပါသည်။", accent: "blue", caseKey: "address_support" },
];
const steps = [["၀၁", "အမှန်တကယ်အခက်အခဲကို ဖော်ပြပါ", "ပလက်ဖောင်းနှင့် အခက်အခဲအမျိုးအစားကို ရွေးချယ်ပြီး မည်သည့်အဆင့်တွင် ရပ်တန့်နေသည်ကို ရှင်းလင်းစွာ ဖော်ပြပါ။"], ["၀၂", "ရှင်းလင်းသော လမ်းကြောင်း ရယူပါ", "လိုအပ်ချက်စာရင်း၊ သတိပြုရန်အချက်များနှင့် နောက်တစ်ဆင့်အတွက် အကြံပြုချက်ကို ရရှိပါမည်။"], ["၀၃", "တောင်းဆိုမှုကို ဆက်လက်စောင့်ကြည့်ပါ", "လုပ်ငန်းတိုးတက်မှုကို တစ်နေရာတည်းတွင် မှတ်တမ်းတင်ထား၍ ပြန်လည်စစ်ဆေးနိုင်ပြီး ဆက်လက်ဆောင်ရွက်နိုင်ပါသည်။"]];
const faqs = [["ပလက်ဖောင်း၏ အတည်ပြုခွင့်ကို အာမခံနိုင်ပါသလား။", "မအာမခံနိုင်ပါ။ အတည်ပြုဆုံးဖြတ်ချက်သည် ပလက်ဖောင်း၏ တာဝန်ဖြစ်ပါသည်။ CreatorHubPlus သည် လိုအပ်ချက်များကို နားလည်စေရန်၊ မှန်ကန်သောအချက်အလက်များကို ပြင်ဆင်ရန်နှင့် ရှောင်ရှားနိုင်သည့် ပြင်ဆင်မှုအမှားများကို လျှော့ချရန်သာ ကူညီပေးပါသည်။"], ["စာရွက်စာတမ်းအတု သို့မဟုတ် အတည်ပြုမှု ရှောင်လွှဲခြင်းကို ကူညီပေးပါသလား။", "မကူညီပေးပါ။ CreatorHubPlus သည် တရားဝင်၊ မှန်ကန်ပြီး အတည်ပြုနိုင်သောအချက်အလက်များကို ပြင်ဆင်ခြင်းအတွက်သာ ကူညီပေးပါသည်။ အတုအယောင် ကိုယ်ရေးအချက်အလက်၊ လိပ်စာစာရွက်စာတမ်းများ သို့မဟုတ် ပလက်ဖောင်းစည်းမျဉ်းများကို ရှောင်လွှဲခြင်း မပြုလုပ်ပါ။"], ["မည်သည့်ပလက်ဖောင်းမှ စတင်နိုင်ပါသလဲ။", "အများအသုံးပြုသော ဖန်တီးရှင် သို့မဟုတ် ငွေလက်ခံပလက်ဖောင်းမှ စတင်နိုင်ပါသည်။ လက်တွေ့အခက်အခဲကို ဖော်ပြပေးပါ။ ဝန်ဆောင်မှုအကန့်အသတ်ပြင်ပဖြစ်ပါက မရှင်းလင်းသောကတိကဝတ်မပြုဘဲ တိတိကျကျ အသိပေးပါမည်။"], ["အကူအညီမတောင်းမီ မည်သည့်အချက်များ ပြင်ဆင်ထားသင့်ပါသလဲ။", "ပလက်ဖောင်းအမည်၊ လက်ရှိစာမျက်နှာအခြေအနေ၊ အရေးကြီးအချက်အလက်များကို ဖုံးကွယ်ထားသော အမှားပြသမျက်နှာပုံနှင့် ယခင်ကြိုးစားခဲ့သည့်အဆင့်များကို ပြင်ဆင်ထားပါ။"]];
function BrandGlyph({ icon }: { icon: SimpleIcon }) { return <svg viewBox="0 0 24 24" aria-hidden="true"><path d={icon.path} fill="currentColor" /></svg>; }
function scrollTo(target: string) { document.querySelector(target)?.scrollIntoView({ behavior: "smooth", block: "start" }); }
function openCookiePreferences() { window.CookieConsent?.showPreferences?.(); }

export default function BurmeseHome() {
  useSiteLocale("my", "CreatorHubPlus — အွန်လိုင်းဝင်ငွေနှင့် ငွေလက်ခံရေး အကူအညီ");
  const [menuOpen, setMenuOpen] = useState(false); const [selectedService, setSelectedService] = useState("ပလက်ဖောင်း ဝင်ငွေ"); const [caseDialogOpen, setCaseDialogOpen] = useState(false);
  const selectedServiceRecord = services.find((service) => service.title === selectedService) ?? services[0];
  const chooseService = (service: string) => { setSelectedService(service); scrollTo("#start"); };
  return <div className="payout-site my-site" id="top">
    <header className="payout-header"><a href="#top" className="payout-brand" onClick={() => scrollTo("#top")}><img src={logo} alt="CreatorHubPlus" /><span>creatorhub<span>plus</span></span></a><nav className="payout-nav" aria-label="အဓိက လမ်းညွှန်"><a href="#services" onClick={() => scrollTo("#services")}>ဝန်ဆောင်မှုများ</a><a href="#how" onClick={() => scrollTo("#how")}>လုပ်ငန်းစဉ်</a><a href="#trust" onClick={() => scrollTo("#trust")}>စည်းကမ်းနှင့် ယုံကြည်စိတ်ချရမှု</a><a href="#faq" onClick={() => scrollTo("#faq")}>အကူအညီ</a><Link href="/account" className="workspace-nav-link">ကိုယ်ပိုင်ဗဟို</Link><Link href="/workspace" className="workspace-nav-link">အလုပ်ခွင်</Link></nav><div className="payout-actions"><Link href="/" className="language-link">English</Link><Link href="/payment" className="payment-nav-link">ငွေပေးချေမှု တောင်းဆိုရန်</Link><button className="header-cta" onClick={() => scrollTo("#start")}>အကူအညီတောင်းဆိုရန် <ArrowUpRight size={15} /></button><button className="payout-menu" aria-label="လမ်းညွှန်ဖွင့်ရန်" onClick={() => setMenuOpen((open) => !open)}>{menuOpen ? <X size={19} /> : <Menu size={20} />}</button></div>{menuOpen && <div className="payout-mobile-menu">{[["ဝန်ဆောင်မှုများ", "#services"], ["လုပ်ငန်းစဉ်", "#how"], ["စည်းကမ်းနှင့် ယုံကြည်စိတ်ချရမှု", "#trust"], ["အကူအညီ", "#faq"]].map(([label, target]) => <button key={label} onClick={() => { setMenuOpen(false); scrollTo(target); }}>{label}<ArrowUpRight size={17} /></button>)}<Link href="/account" onClick={() => setMenuOpen(false)}>ကိုယ်ပိုင်ဗဟို<ArrowUpRight size={17} /></Link><Link href="/workspace" onClick={() => setMenuOpen(false)}>အလုပ်ခွင်<ArrowUpRight size={17} /></Link></div>}</header>
    <main>
      <section className="payout-hero"><div className="hero-copy-payout"><p className="payout-eyebrow"><span /> မြန်မာဖန်တီးရှင်များနှင့် အွန်လိုင်းလုပ်ငန်းများအတွက်</p><h1>အွန်လိုင်းမှ ဝင်ငွေ ရယူပါ။<br /><em>ငွေလက်ခံပါ။</em><br />အကောင့်ကို စနစ်တကျ ပြင်ဆင်ပါ။</h1><p className="hero-detail">CreatorHubPlus သည် မြန်မာနိုင်ငံရှိ ဖန်တီးရှင်များနှင့် အွန်လိုင်းလုပ်ငန်းများအတွက် ဝင်ငွေရရှိရေး၊ ငွေလက်ခံရေး၊ အကောင့်ပြင်ဆင်ရေးနှင့် အတည်ပြုနိုင်သောလိပ်စာဆိုင်ရာ လိုအပ်ချက်များကို တစ်ဆင့်ချင်း စနစ်တကျ နားလည်ဆောင်ရွက်နိုင်ရန် ကူညီပေးပါသည်။</p><div className="hero-ctas"><button className="coral-button" onClick={() => scrollTo("#start")}>အခက်အခဲကို ဖော်ပြရန် <ArrowUpRight size={17} /></button><button className="quiet-button" onClick={() => scrollTo("#services")}>ဝန်ဆောင်မှုများ <ArrowDownRight size={17} /></button></div><p className="hero-rule"><ShieldCheck size={15} /> တရားဝင်အသုံးပြုမှုအတွက်သာ ကူညီပေးပါသည်။ အတုအယောင်စာရွက်စာတမ်းနှင့် စည်းမျဉ်းရှောင်လွှဲမှုများ မပြုလုပ်ပါ။</p></div><div className="payout-map" aria-label="ပလက်ဖောင်းမှ ငွေလက်ခံရေး လမ်းကြောင်း"><div className="map-topline"><span>သင့်ပလက်ဖောင်း လမ်းကြောင်း</span><i /><span>၀၁ / ၀၄</span></div><div className="platform-badge platform-one"><span><BrandGlyph icon={siFacebook} /></span> Facebook</div><div className="platform-badge platform-two"><span><BrandGlyph icon={siYoutube} /></span> YouTube</div><div className="platform-badge platform-three"><span><BrandGlyph icon={siTiktok} /></span> TikTok</div><div className="platform-badge platform-four"><span><BrandGlyph icon={siPaypal} /></span> PayPal</div><div className="route-line route-one" /><div className="route-line route-two" /><div className="route-line route-three" /><div className="route-line route-four" /><div className="route-hub"><img src={logo} alt="" /><strong>အကူအညီ လမ်းကြောင်း</strong><span>စစ်ဆေး → ပြင်ဆင် → ဆက်လက်လုပ်ဆောင်</span></div><div className="route-status"><BadgeCheck size={16} /><span>အမှန်တကယ်<br /><b>လိုအပ်ချက်မှ စတင်ပါ</b></span></div><div className="map-foot"><span>ပလက်ဖောင်း</span><b>→</b><span>လိုအပ်ချက်စာရင်း</span><b>→</b><span>နောက်တစ်ဆင့်</span></div></div></section>
      <section className="payment-section" aria-label="ငွေလက်ခံနည်းလမ်းများ"><div className="payment-section-banner"><div><p className="payout-eyebrow light"><span /> ငွေလက်ခံ လမ်းကြောင်းများ</p><h2>နည်းလမ်းကို ရွေးချယ်ပါ။<br /><em>လမ်းကြောင်းကို ရှင်းလင်းစေပါ။</em></h2></div><div className="payment-banner-note"><span>၀၁ / ၀၃</span><p>ဒေသတွင်း e-wallet များနှင့် ဘဏ်များကို တောင်းဆိုမှုလမ်းကြောင်းတစ်ခုအတွင်း စနစ်တကျ စီစဉ်ထားပါသည်။</p></div></div><section className="payment-methods-rail" aria-label="လက်ခံနိုင်သော ငွေလက်ခံနည်းလမ်းများ"><div className="payment-rail-intro"><p>ငွေလက်ခံနည်းလမ်းကို ရွေးချယ်ပါ</p><span>အသုံးပြုလိုသည့် e-wallet သို့မဟုတ် ဘဏ်ကိုရွေးချယ်ပြီး လိုအပ်သောအချက်အလက်များနှင့် နောက်တစ်ဆင့်ကို စနစ်တကျ စစ်ဆေးရန် အကူအညီတောင်းဆိုမှု စတင်ပါ။</span></div><div className="payment-rail-window"><div className="payment-rail-track">{[0, 1].map((repeat) => <div className="payment-rail-set" key={repeat} aria-hidden={repeat === 1}>{payments.map((method) => <div className={`payment-method ${method.kind}${method.label === "Bangkok Bank" ? " bangkok-bank" : ""}`} key={`${method.label}-${repeat}`}><img src={method.logo} alt={repeat === 1 ? "" : `${method.label} official logo`} /></div>)}</div>)}</div></div><p className="payment-rail-disclaimer">အမှတ်တံဆိပ်အမည်များနှင့် Logo များသည် သက်ဆိုင်ရာပိုင်ရှင်များ၏ ပိုင်ဆိုင်မှုဖြစ်ပါသည်။ ငွေလက်ခံလမ်းကြောင်း ခွဲခြားသတ်မှတ်ရန်အတွက်သာ ပြသထားခြင်းဖြစ်ပြီး မိတ်ဖက်ဆက်ဆံရေးကို မဆိုလိုပါ။</p></section></section>
      <section className="service-section" id="services"><div className="section-top-payout"><div><p className="payout-eyebrow">ကျွန်ုပ်တို့ ကူညီပေးနိုင်သည့် အချက်များ</p><h2>အမှန်တကယ်ကြုံတွေ့ရသော ပြဿနာလေးမျိုး။<br /><em>ရှင်းလင်းသော စတင်ရာတစ်ခု။</em></h2></div><p>သာမန် “ဒစ်ဂျစ်တယ်ဝန်ဆောင်မှု” မဟုတ်ဘဲ အွန်လိုင်းဝင်ငွေကို နှောင့်နှေးစေသော အမှန်တကယ်မေးခွန်းများကို အခြေခံ၍ စီစဉ်ထားပါသည်။</p></div><div className="service-grid-payout">{services.map(({ id, icon: Icon, title, subtitle, state, next, description, accent, caseKey }) => <article className={`payout-service-card ${accent}`} key={title}><div className="service-card-head"><span>{id}</span><p>အဆင့် / {state}</p><Icon size={20} strokeWidth={1.65} /></div><i className="service-route" /><p className="service-subtitle">{subtitle}</p><h3>{title}</h3><p className="service-description">{description}</p><p className="service-next"><span>နောက်တစ်ဆင့်</span>{next}</p><div className="service-file-end"><span>တောင်းဆိုမှုအတွက် အဆင်သင့်</span><div className="service-card-actions"><button onClick={() => chooseService(title)}>လမ်းကြောင်းဖွင့်ရန် <ArrowUpRight size={16} /></button><Link className="service-payment-link" href={`/payment?service=${caseKey}`}>ဤဝန်ဆောင်မှုအတွက် ငွေပေးချေရန် <ArrowUpRight size={15} /></Link></div></div></article>)}</div></section>
      <section className="case-section" id="start"><div className="case-intro"><p className="payout-eyebrow"><span /> အကူအညီတောင်းဆိုမှု စတင်ရန်</p><h2>သင် ဖြေရှင်းလိုသည့်<br /><em>အချက်မှာ အဘယ်နည်း။</em></h2><p>အနီးစပ်ဆုံးလမ်းကြောင်းကို ရွေးချယ်ပါ။ ဤလုပ်ဆောင်ချက်သည် ရလဒ်ကို အာမခံခြင်းမဟုတ်ဘဲ မိမိအခြေအနေအတွက် ရှင်းလင်းသော စတင်ရာတစ်ခုကို ဖန်တီးပေးခြင်းဖြစ်ပါသည်။</p></div><div className="case-chooser"><div className="case-choice-grid">{services.map(({ title, id, icon: Icon }) => <button key={title} className={selectedService === title ? "selected" : ""} onClick={() => setSelectedService(title)}><span>{id}</span><Icon size={18} /><strong>{title}</strong><i><Check size={14} /></i></button>)}</div><div className="case-selection"><p>ရွေးချယ်ထားသော စတင်ရာ</p><h3>{selectedService}</h3><p>လိုအပ်ချက်၊ ပါဝင်သည့် စာရွက်စာတမ်း သို့မဟုတ် ဆက်တင်များနှင့် တရားဝင် နောက်တစ်ဆင့်ကို ဦးစွာ စနစ်တကျ စီစဉ်နိုင်ရန် ကူညီပေးပါမည်။</p><button className="navy-button" onClick={() => setCaseDialogOpen(true)}>ဤတောင်းဆိုမှုဖြင့် ဆက်လက်ရန် <ArrowUpRight size={17} /></button></div></div></section>
      <section className="how-section" id="how"><div className="how-header"><p className="payout-eyebrow">တောင်းဆိုမှု ဆက်လက်လုပ်ဆောင်ပုံ</p><h2>ခန့်မှန်းရမှု နည်းစေပါ။<br /><em>လုပ်ငန်းတိုးတက်မှုကို မြင်သာစေပါ။</em></h2></div><div className="how-steps">{steps.map(([num, title, description]) => <article key={num}><span>{num}</span><i /><h3>{title}</h3><p>{description}</p></article>)}</div></section>
      <section className="trust-section" id="trust"><div className="trust-statement"><p className="payout-eyebrow light"><span /> ယုံကြည်စိတ်ချရမှုသည် ဝန်ဆောင်မှု၏ အစိတ်အပိုင်းဖြစ်သည်</p><h2>ကောင်းမွန်သော လမ်းကြောင်းသည်<br /><em>အန္တရာယ်ရှိသော အလွယ်နည်း မဟုတ်ပါ။</em></h2><p>CreatorHubPlus သည် ပလက်ဖောင်းလိုအပ်ချက်များကို နားလည်စေရန်နှင့် မှန်ကန်သောအချက်အလက်များကို ပြင်ဆင်ရန် ကူညီပေးပါသည်။ စာရွက်စာတမ်းအတု ပြုလုပ်ခြင်း၊ အတည်ပြုမှု ရှောင်လွှဲခြင်း၊ အခြားသူအဖြစ် ဟန်ဆောင်ခြင်း သို့မဟုတ် အတည်ပြုခွင့် အာမခံခြင်း မပြုလုပ်ပါ။</p><button onClick={() => scrollTo("#faq")}>ဝန်ဆောင်မှုစည်းကမ်းများ ဖတ်ရှုရန် <ArrowDownRight size={17} /></button></div><div className="trust-list"><article><ShieldCheck size={25} /><h3>တရားဝင်အသုံးပြုမှု</h3><p>အကြံပြုချက်တိုင်းသည် ပလက်ဖောင်းစည်းမျဉ်းများနှင့် မှန်ကန်သော အကောင့်အချက်အလက်များအပေါ် အခြေခံပါသည်။</p></article><article><FileCheck2 size={25} /><h3>ရှင်းလင်းသော ပြင်ဆင်မှု</h3><p>အချိန်မကုန်မီ မည်သည့်စာရွက်စာတမ်းနှင့် ဆက်တင်များ အရေးကြီးသည်ကို သိရှိနိုင်ပါသည်။</p></article><article><MessageCircleMore size={25} /><h3>ရိုးရှင်းသော ရှင်းလင်းချက်</h3><p>နည်းပညာဆန်သော မလိုအပ်သည့်စကားလုံးများနှင့် မရှင်းလင်းသောကတိကဝတ်မပါဘဲ နောက်တစ်ဆင့်ကို နားလည်နိုင်ပါသည်။</p></article></div></section>
      <section className="faq-section" id="faq"><div className="faq-title"><p className="payout-eyebrow">စတင်မတိုင်မီ သိရှိသင့်သောအချက်များ</p><h2>အကူအညီတောင်းဆိုမှု<br />မစတင်မီ။</h2><CircleHelp size={34} /></div><div className="faq-list">{faqs.map(([question, answer]) => <details key={question}><summary>{question}<ChevronDown size={18} /></summary><p>{answer}</p></details>)}</div></section>
      <section className="contact-panel"><div><p className="payout-eyebrow light">အမှန်တကယ်လိုအပ်ချက်ရှိချိန်တွင်</p><h2>ပလက်ဖောင်းကို ယူဆောင်လာပါ။<br /><em>နောက်တစ်ဆင့်ကို စနစ်တကျ ချမှတ်ပေးပါမည်။</em></h2></div><div><p>ရှည်လျားသောဖောင်မလိုအပ်ပါ။ အခြေအနေတစ်ခုမှ စတင်၍ လမ်းကြောင်းကို ပိုမိုရှင်းလင်းစေပါမည်။</p><button onClick={() => scrollTo("#start")}>အကူအညီတောင်းဆိုမှု စတင်ရန် <ArrowUpRight size={18} /></button></div></section>
    </main>
    <CaseIntakeDialog open={caseDialogOpen} serviceKey={selectedServiceRecord.caseKey as CaseServiceKey} serviceLabel={selectedServiceRecord.title} locale="my" onClose={() => setCaseDialogOpen(false)} />
    <footer className="payout-footer"><div className="footer-logo-line"><a href="#top" className="payout-brand" onClick={() => scrollTo("#top")}><img src={logo} alt="CreatorHubPlus" /><span>creatorhub<span>plus</span></span></a><p>မြန်မာဖန်တီးရှင်များအတွက် အွန်လိုင်းဝင်ငွေ၊ ငွေလက်ခံရေးနှင့် အကောင့်ပြင်ဆင်ရေး အကူအညီ။</p></div><div className="footer-columns"><div><b>စတင်ရန်</b><a href="#services" onClick={() => scrollTo("#services")}>ဝန်ဆောင်မှုများ</a><a href="#start" onClick={() => scrollTo("#start")}>အကူအညီတောင်းဆိုရန်</a><a href="#how" onClick={() => scrollTo("#how")}>လုပ်ငန်းစဉ်</a></div><div><b>ဝန်ဆောင်မှုစည်းကမ်းများ</b><a href="#trust" onClick={() => scrollTo("#trust")}>စည်းကမ်းနှင့် ယုံကြည်စိတ်ချရမှု</a><a href="#faq" onClick={() => scrollTo("#faq")}>မေးခွန်းများ</a><Link href="/my/privacy">ကိုယ်ရေးအချက်အလက် မူဝါဒ</Link><button onClick={openCookiePreferences}>Cookie ဆက်တင်များ စီမံရန်</button></div><div className="footer-note"><Sparkles size={17} /><p>ရှင်းလင်းသော လုပ်ဆောင်မှုသည် အလျင်အမြန်ကတိကဝတ်ထက် ပိုမိုတန်ဖိုးရှိပါသည်။</p></div></div><div className="footer-base"><span>© ၂၀၂၆ CreatorHubPlus</span><span>တတိယပါတီပလက်ဖောင်းများနှင့် မိတ်ဖက်ဆက်ဆံရေး မရှိပါ။</span></div></footer>
  </div>;
}
